Int2018 67 photo storage service
AvaSpa/VikinQuiz pull request #15
Opened 2018-08-21 10:40 UTC by Slitthe

2018-08-21 12:36 UTC, vasi-axinte requested changes

2018-08-21 12:36 UTC, vasi-axinte commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +        public async Task<IActionResult> Put(NewQuizViewModel quizBodyData, int id)
this method is too long. Try to split it in several smaller methods for better maintainability and readability

2018-08-22 09:06 UTC, vasi-axinte requested changes

2018-08-22 09:06 UTC, vasi-axinte commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +        class UploadAndDeleteData
Why do you need to use nested classes?

2018-08-22 09:50 UTC, AndronicMonica commented on VikingQuiz.Api/Controllers/QuizzesController.cs
>              return Ok(new { quizVm.Id, quizVm.Title, quizVm.PictureUrl });
I don't understand why you are returning a new quizVm. Maybe you could just return quizVm, like return Ok(quizVm).

2018-08-22 09:50 UTC, AndronicMonica commented on VikingQuiz.Api/Controllers/QuizzesController.cs
>              });
The table Quiz has a column named LastModified which is null by default. Maybe when you create a new quiz you should set the value to current date and time.

2018-08-22 09:50 UTC, AndronicMonica commented on VikingQuiz.Api/Controllers/QuizzesController.cs
>              });
Again, the thing with LastModified column which should be updated to current date and time

2018-08-22 09:50 UTC, AndronicMonica commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +        public async Task<IActionResult> Put(NewQuizViewModel quizBodyData, int id)
Can you please rename this method. Maybe UpdateQuiz would be more suggestive

2018-08-23 07:37 UTC, vasi-axinte requested changes

2018-08-23 07:37 UTC, vasi-axinte commented on VikingQuiz.Api/Utilities/AzureBlobService.cs
> +        private string getFileExtension(string contentType)
This does not comply with the naming conventions of methods.

2018-08-23 07:37 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/QuestionsComponent/MainQuestionComponent/MainQuestionComponent.tsx
> +   public apiEndpoint = "http://localhost:60151/api/storage/";
This will not work in production. Please use the constant apiUrl

2018-08-23 10:54 UTC, andrianwritek requested changes

2018-08-23 10:54 UTC, andrianwritek commented on VikingQuiz.Api/Controllers/QuizzesController.cs
>              var quizzes = quizRepository.GetQuizByUserId(currentUserId);
GetQuizByUserId - tells 1 quiz not a list, fix naming pls

2018-08-23 10:54 UTC, andrianwritek commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +            if (quiz == null || quiz.UserId != currentUserId)
GetQuizForUser(int quizId, int userId)
and check on single null

2018-08-23 10:54 UTC, andrianwritek commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +            UploadAndDeleteData uploadAndDeleteResult = await uploadAndDeletePhoto(id, quizBodyData.Files[0]);
uploadAndDeletePhoto
Uploads and delete uplaoded photo or correct is "OverritePhoto" or "AddOrUpdate" or "DeleteAndUpload" <- to actions is bad but sometimes is acceptble

2018-08-23 10:54 UTC, andrianwritek commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +                blobService.DeletePhotoAsync(deletedQuiz.PictureUrl);
no await?

2018-08-23 10:54 UTC, andrianwritek commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +            Quiz updatedQuiz = quizRepository.UpdateQuiz(newQuizData);
update and if null not exist? update means to do action Update and return updated value, Update doesnt have check if exist, separate logic please

2018-08-23 10:54 UTC, andrianwritek commented on VikingQuiz.Api/Controllers/QuizzesController.cs
> +        private string azureContainerName = "users";
move top

2018-08-23 11:42 UTC, andrianwritek approved these changes

2018-08-23 11:42 UTC, merged