Not found page
AvaSpa/VikinQuiz pull request #4
Opened 2018-08-01 09:12 UTC by Dumitrescu-Dragos

2018-08-01 13:14 UTC, vasi-axinte requested changes

2018-08-01 13:14 UTC, vasi-axinte commented on VikingQuiz.Api/Utilities/UserExtensions.cs
> +            var strId = user.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
Try to use first letter of the entity name in lambda expressions (i.e. u instead of x)

2018-08-01 13:14 UTC, vasi-axinte commented on VikingQuiz.Api/Utilities/UserExtensions.cs
>              return int.Parse(strId);
Please use full name for variables, do not abreviate them

2018-08-02 07:30 UTC, andrianwritek commented on VikingQuiz.UI/src/Components/NotFoundComponent/NotFoundComponent.tsx
> +const notFoundComponent: any = (props: any) => {
component with uppercase

2018-08-02 07:30 UTC, andrianwritek commented on VikingQuiz.UI/src/Components/NotFoundComponent/NotFoundComponent.tsx
> +export default notFoundComponent;
component with uppercase

2018-08-02 07:30 UTC, andrianwritek commented on VikingQuiz.UI/src/Components/NotFoundComponent/NotFoundComponent.tsx
> +          <footer><BottomLogo /></footer>
why footer and logo is there, it must be in master render?

2018-08-03 07:33 UTC, vasi-axinte approved these changes

2018-08-03 07:33 UTC, vasi-axinte commented
Everything is cool, but solve the conflict first. After that, we can merge this branch into develop

2018-08-03 09:25 UTC, merged