Int2018 23 48 password reset
AvaSpa/VikinQuiz pull request #7
Opened 2018-08-06 12:49 UTC by andiabrudan

2018-08-06 13:13 UTC, vasi-axinte requested changes

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.Api/Controllers/EmailController.cs
> +            // we want the 'confirm email' token to be valid for 168 / 24 = 7 days
Can`t we find a better way to say this instead of leaving comments?

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.Api/Controllers/EmailController.cs
> +            string Body = "Click the following link to register your account\n\nhttp://localhost:3000/confirm/" + token;
Please extract the url into a constant and concatenate it to the Body string. That way, in case you want to change the URL, it will be way easier.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.Api/Controllers/EmailController.cs
> +            string Body = "Click the following link to reset your password\n\nhttp://localhost:3000/forgot/" + token +
Same observation regarding the URL here.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.Api/Controllers/EmailController.cs
> +            // we want the 'reset password' token to only last 5 hours
Maybe we can write this in a way that wouldn`t need comments?

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.Api/Repositories/UserRepository.cs
> +            return context.User.FirstOrDefault(x => x.Email == email);
Please use a more meaningful letter for the lambda expression. Usually it is a good practice to use the first letter of the entity it represents. In this case, I think "u" is the letter.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.Api/Utilities/AutheticationService.cs
>          private readonly VikinQuizContext context;
Why do you use different conventions for variables with same access level?

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.css
> +.submitButton{
This should use kebab-case naming.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.tsx
> +    // we need to get the token from the url so we know how the user is
Please remove comments from code if they are not critical.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.tsx
> +    private onClickHandler = (url: any, formData: any) => {
This is method is a bit long. Can we maybe split it in smaller methods?

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/SendEmailComponent/SendEmailComponent.tsx
> +            statusMessage: '' // the message to show after we call the server to send resend link
Please remove these kind of comments. A variable shouldn`t require a comment for one to know its meaning.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/SendEmailComponent/SendEmailComponent.tsx
> +                        buttonName=''
Please extract this url into a constant.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/SendEmailComponent/SendEmailComponent.tsx
> +        console.log(formData);
Please don`t forget console logs through your code. Also, const should be declare  first in a function (i.e. right after the { )

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/LoginFormComponent/LoginFormComponent.tsx
> +          <a href="/forgot" className="forget-pass col-xs-6">FORGOT PASSWORD</a>
Please extract the string into a constant so we can change it easily in the future if it is necessary.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/entities/Validation/validators.tsx
> +    const confPass = funcs.getItemById("conf-password", inputs).item;
Please don`t use abbreviations in variable names.

2018-08-06 13:13 UTC, vasi-axinte commented on VikingQuiz.UI/src/entities/Validation/validators.tsx
> +    const inputsCopy = funcs.getCopyOfInputs(inputs);
What does inputs represent? Please find more meaningful names.

2018-08-07 11:35 UTC, vasi-axinte requested changes

2018-08-07 11:35 UTC, vasi-axinte commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.tsx
> +        this.apiAddress = 'http://localhost:60151/api/email/';
Why do you assign the apiAddress only here?

2018-08-07 11:35 UTC, vasi-axinte commented on VikingQuiz.UI/src/entities/Validation/validators.tsx
> +   const inputFieldsValueCopy = funcs.getCopyOfInputs(inputs);
What do the inputFields mean? What are they and what is their purpose?

2018-08-07 11:35 UTC, vasi-axinte commented on VikingQuiz.Api/Controllers/EmailController.cs
> +            string registerAccountAddress = "http://localhost:3000/confirm/" + token;
Why isn`t the url extracted in a constant and the endpoint built using concatenation?

2018-08-09 11:57 UTC, AvaSpa reviewed
Take more care with displayed text.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.Api/Controllers/EmailController.cs
> +                return BadRequest("your new password cannot be the same as the old one");
If this is a message that is directly displayed, make it look good here. Capital first letter, punctuation.
I this message is not displayed, return a code and treat it in the client.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.Api/Models/User.cs
> +        public bool IsConfirmed { get; set; } = false;
Boolean variables are false by default.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.Api/Utilities/AutheticationService.cs
> +        internal User GetUserByCredentials(string email, string password)
Unless you really need to make this method accessible only in the current assembly, leave it public.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.css
> +	user-select: none;
Format the code. Alignment.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.tsx
> +                <div className='yellow-bg-message'>update password</div>
Unless specified otherwise in the design, all displayed text must be properly written. Capital first letter in this case.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.tsx
> +                this.setState({ statusMessage: 'This reset link is invalid has expired' });
Proper text: 'This reset link is invalid has expired' should be "'This reset link is invalid or has expired.'"

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/ResetPasswordComponent/ResetPasswordComponent.tsx
> +            this.setState({ statusMessage: 'Could not connect to server. Please try again later' });
Sentence end punctuation.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/SendEmailComponent/SendEmailComponent.css
> +	user-select: none;
Format the code. Alignment.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/SendEmailComponent/SendEmailComponent.tsx
> +            this.setState({ statusMessage: 'Could not connect to server. Please try again later' });
Sentence end punctuation.

2018-08-09 11:57 UTC, AvaSpa commented on VikingQuiz.UI/src/Components/ForgotPasswordComponent/SendEmailComponent/SendEmailComponent.tsx
> +            this.setState({ statusMessage: 'This email is not registered with us' });
Sentence end punctuation.

2018-08-10 07:28 UTC, AvaSpa approved these changes

2018-08-10 07:36 UTC, vasi-axinte approved these changes

2018-08-10 07:36 UTC, merged